# Generated by Django 4.2.4 on 2023-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('labs', models.IntegerField()),
                ('lectures', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('classes', models.IntegerField()),
                ('classId', models.CharField(max_length=10)),
            ],
        ),
    ]
