# Generated by Django 4.2.4 on 2023-12-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('info', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('div', models.CharField(max_length=1)),
                ('teacherid', models.CharField(max_length=5)),
            ],
        ),
    ]
